services:
  backend_rds:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend_rds:${IMAGE_TAG}"
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend_redis:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend_redis:${IMAGE_TAG}"
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:${IMAGE_TAG}"
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - backend_rds
      - backend_redis